name: resta_dash_workspace
description: "A workspace for Resta Dash applications and shared packages."
publish_to: none

environment:
  sdk: 3.8.1

workspace:
  - apps/resta_dash
  # - apps/resta_dash_waiter
  - packages/core_functionality
  - packages/shared_ui
  - packages/database
  - packages/log_cat

dependencies:
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
