name: resta_dash
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # UI
  gap: ^3.0.1
  flutter_animate: ^4.5.2
  flex_color_scheme: ^8.2.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  skeletonizer: ^2.1.0+1
  flutter_form_builder: ^10.1.0
  omni_datetime_picker: ^2.3.1
  flutter_staggered_grid_view: ^0.7.0
  animated_read_more_text: ^0.0.6
  toastification: ^2.3.0
  pull_to_refresh: ^2.0.0
  animated_segmented_tab_control: ^2.0.0
  pull_down_button: ^0.10.2
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  # State Management
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  get_it: ^8.2.0
  go_router: ^16.1.0
  event_bus: ^2.0.1
  equatable: ^2.0.7
  # File/Storage
  # hive_ce: ^2.11.3
  # hive_ce_flutter: ^2.3.1
  # shared_preferences: ^2.5.3
  # Network
  # dio: ^5.9.0
  # dio_cache_interceptor: ^4.0.3
  # http_cache_hive_store: ^5.0.1
  # Utility
  # shared_preferences_annotation:
  #   git:
  #     url: https://github.com/Ahnaf16/shared_preferences_gen.git
  #     path: packages/shared_preferences_annotation
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  recase: ^4.1.0
  url_launcher: ^6.3.2
  fpdart: ^1.1.1
  collection: ^1.19.1
  intl: ^0.20.2
  form_builder_validators: ^11.2.0
  scaled_app: ^2.3.0
  faker: ^2.2.0
  timeago: ^3.7.1
  cached_network_image: ^3.4.1
  flutter_localized_locales: ^2.0.5

  #local
  database: 0.0.1
  core_functionality: 0.0.1
  shared_ui: 0.0.1
  log_cat: 0.0.1
  hive_ce_flutter: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  slang_build_runner: ^4.8.0
  hive_ce_generator: ^1.9.2
  build_runner: ^2.4.15
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  # shared_preferences_gen:
  #   git:
  #     url: https://github.com/Ahnaf16/shared_preferences_gen.git
  #     path: packages/shared_preferences_gen

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/raster/
    - assets/svg/
    - assets/icon/
    - assets/icon/duo_tone/

flutter_gen:
  output: lib/_core/strings/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
