name: shared_ui
description: "A new Flutter package project."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  gap: ^3.0.1
  flutter_animate: ^4.5.2
  flex_color_scheme: ^8.2.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  skeletonizer: ^2.1.0+1
  flutter_form_builder: ^10.1.0
  omni_datetime_picker: ^2.3.1
  flutter_staggered_grid_view: ^0.7.0
  animated_read_more_text: ^0.0.6
  toastification: ^2.3.0
  pull_to_refresh: ^2.0.0
  animated_segmented_tab_control: ^2.0.0
  pull_down_button: ^0.10.2
  cached_network_image: ^3.4.1

  # local
  core_functionality: 0.0.1
  log_cat: 0.0.1
  database: 0.0.1
  form_builder_validators: ^11.2.0
  go_router: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
