name: database
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.1.1
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.3
  http_cache_hive_store: ^5.0.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  shared_preferences: ^2.5.3
  shared_preferences_annotation:
    git:
      url: https://github.com/Ahnaf16/shared_preferences_gen.git
      path: packages/shared_preferences_annotation

  #local
  core_functionality: 0.0.1
  log_cat: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.2
  build_runner: ^2.4.15
  shared_preferences_gen:
    git:
      url: https://github.com/Ahnaf16/shared_preferences_gen.git
      path: packages/shared_preferences_gen
