// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    // registerAdapter(CuisineAdapter());
    // registerAdapter(DailySpecialAdapter());
    // registerAdapter(DishAdapter());
    // registerAdapter(HomeDataAdapter());
    // registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    // registerAdapter(CuisineAdapter());
    // registerAdapter(DailySpecialAdapter());
    // registerAdapter(DishAdapter());
    // registerAdapter(HomeDataAdapter());
    // registerAdapter(UserAdapter());
  }
}
